version: 0.2
phases:
  pre_build:
    commands:
      - echo Instalando dependencias
  build:
    commands:
      - echo Build iniciado em `date`
  post_build:
    commands:
      - echo Build finalizado em `date`
artifacts:
  files:
    - app/**/*
    - appspec.yml
    - scripts/**/*  #levar tudo que tem dentro dela